version: '3'

services:
  backend:
    build:
      context: ./dev/backend/
      args:
        packagename: "github.com/class/pizza"
    volumes:
      - ./:/backend
    ports:
      - "8080"
    links:
      - database
    environment:
      GOBIN: /go/bin
      EYELOG_FLAGS_DEFAULT: shortfile
      PIZZA_LISTEN_PORT: 8080
      PIZZA_ENVIRONMENT: development
      PIZZA_BASE_URL: "http://localhost"
      PIZZA_VERSION: "2.1"
      PIZZA_DB_HOST: database
      PIZZA_DB_USERNAME: root
      PIZZA_DB_DATABASE: pizza
    logging:
      options:
        max-size: "50k"

  httpd:
    image: httpd:2.4.33
    volumes:
      - ./dev/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./webroot:/usr/local/apache2/htdocs
      - ./ui:/usr/local/apache2/htdocs/ui
    ports:
      - "80:80"
    links:
      - backend
    logging:
      options:
        max-size: "1k"

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./schema:/schema
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: pizza
    logging:
      options:
        max-size: "5k"
  ng:
    image: eyesore/ng:6.0.7
    ports:
      - "9876:9876"
    volumes:
      - ./ui:/ng
    entrypoint:
      - sh
      - -c
      - npm i && ng build --watch --aot --common-chunk --source-map --show-circular-dependencies --vendor-chunk --preserve-symlinks
    logging:
      options:
        max-size: "5k"
